package io.github.kylinhunter.commons.images.constant;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * @author BiJi'an
 * @description
 * @date 2024-01-01 00:34
 */
@RequiredArgsConstructor
@Getter
public enum Format {
  _3FR("3fr", "r--", "Hasselblad Photo RAW"),
  _8BIM("8bim", "rw-", "Photoshop resource format"),
  _8BIMTEXT("8bimtext", "rw-", "Photoshop resource text format"),
  _8BIMWTEXT("8bimwtext", "rw-", "Photoshop resource wide text format"),
  APP1("app1", "rw-", "Raw application information"),
  APP1JPEG("app1jpeg", "rw-", "Raw JPEG binary data"),
  ART("art", "r--", "PF1: 1st Publisher"),
  ARW("arw", "r--", "Sony Alpha DSLR RAW"),
  AVS("avs", "rw+", "AVS X image"),
  BIE("bie", "rw-", "Joint Bi-level Image experts Group interchange format"),
  BMP("bmp", "rw+", "Microsoft Windows bitmap image"),
  BMP2("bmp2", "-w-", "Microsoft Windows bitmap image v2"),
  BMP3("bmp3", "-w-", "Microsoft Windows bitmap image v3"),
  CACHE("cache", "---", "Magick Persistent Cache image format"),
  CALS("cals", "rw-", "Continuous Acquisition and Life-cycle Support Type 1 image"),
  CAPTION("caption", "r--", "Caption (requires separate size info)"),
  CIN("cin", "rw-", "Kodak Cineon Format"),
  CMYK("cmyk", "rw-",
      "Raw cyan, magenta, yellow, and black samples (8 or 16 bits, depending on the image depth)"),
  CMYKA("cmyka", "rw-",
      "Raw cyan, magenta, yellow, black, and matte samples (8 or 16 bits, depending on the image depth)"),
  CR2("cr2", "r--", "Canon Photo RAW"),
  CRW("crw", "r--", "Canon Photo RAW"),
  CUR("cur", "r--", "Microsoft Cursor Icon"),
  CUT("cut", "r--", "DR Halo"),
  DCM("dcm", "r--", "Digital Imaging and Communications in Medicine image"),
  DCR("dcr", "r--", "Kodak Photo RAW"),
  DCX("dcx", "rw+", "ZSoft IBM PC multi-page Paintbrush"),
  DNG("dng", "r--", "Adobe Digital Negative"),
  DPS("dps", "r--", "Display PostScript Interpreter"),
  DPX("dpx", "rw-", "Digital Moving Picture Exchange"),
  EPDF("epdf", "rw-", "Encapsulated Portable Document Format"),
  EPI("epi", "rw-", "Adobe Encapsulated PostScript Interchange format"),
  EPS("eps", "rw-", "Adobe Encapsulated PostScript"),
  EPS2("eps2", "-w-", "Adobe Level II Encapsulated PostScript"),
  EPS3("eps3", "-w-", "Adobe Level III Encapsulated PostScript"),
  EPSF("epsf", "rw-", "Adobe Encapsulated PostScript"),
  EPSI("epsi", "rw-", "Adobe Encapsulated PostScript Interchange format"),
  EPT("ept", "rw-", "Adobe Encapsulated PostScript with MS-DOS TIFF preview"),
  EPT2("ept2", "rw-", "Adobe Level II Encapsulated PostScript with MS-DOS TIFF preview"),
  EPT3("ept3", "rw-", "Adobe Level III Encapsulated PostScript with MS-DOS TIFF preview"),
  EXIF("exif", "rw-", "Exif digital camera binary data"),
  FAX("fax", "rw+", "Group 3 FAX (Not TIFF Group3 FAX!)"),
  FITS("fits", "rw-", "Flexible Image Transport System"),
  FRACTAL("fractal", "r--", "Plasma fractal image"),
  FPX("fpx", "rw-", "FlashPix Format"),
  GIF("gif", "rw+", "CompuServe graphics interchange format"),
  GIF87("gif87", "rw-", "CompuServe graphics interchange format (version 87a)"),
  GRADIENT("gradient", "r--", "Gradual passing from one shade to another"),
  GRAY("gray", "rw+", "Raw gray samples (8/16/32 bits, depending on the image depth)"),
  HISTOGRAM("histogram", "-w-", "Histogram of the image"),
  HRZ("hrz", "r--", "HRZ: Slow scan TV"),
  HTML("html", "-w-", "Hypertext Markup Language and a client-side image map"),
  ICB("icb", "rw+", "Truevision Targa image"),
  ICC("icc", "rw-", "ICC Color Profile"),
  ICM("icm", "rw-", "ICC Color Profile"),
  ICO("ico", "r--", "Microsoft icon"),
  ICON("icon", "r--", "Microsoft icon"),
  IDENTITY("identity", "r--", "Hald CLUT identity image"),
  IMAGE("image", "r--", "GraphicsMagick Embedded Image"),
  INFO("info", "-w+", "Image descriptive information and statistics"),
  IPTC("iptc", "rw-", "IPTC Newsphoto"),
  IPTCTEXT("iptctext", "rw-", "IPTC Newsphoto text format"),
  IPTCWTEXT("iptcwtext", "rw-", "IPTC Newsphoto wide text format"),
  JBG("jbg", "rw+", "Joint Bi-level Image experts Group interchange format"),
  JBIG("jbig", "rw+", "Joint Bi-level Image experts Group interchange format"),
  JNG("jng", "rw-", "JPEG Network Graphics"),
  JP2("jp2", "rw-", "JPEG-2000 JP2 File Format Syntax"),
  JPC("jpc", "rw-", "JPEG-2000 Code Stream Syntax"),
  JPEG("jpeg", "rw-", "Joint Photographic Experts Group JFIF format"),
  JPG("jpg", "rw-", "Joint Photographic Experts Group JFIF format"),
  K25("k25", "r--", "Kodak Photo RAW"),
  KDC("kdc", "r--", "Kodak Photo RAW"),
  LABEL("label", "r--", "Text image format"),
  M2V("m2v", "rw+", "MPEG-2 Video Stream"),
  MAP("map", "rw-", "Colormap intensities and indices"),
  MAT("mat", "r--", "MATLAB image format"),
  MATTE("matte", "-w+", "MATTE format"),
  MIFF("miff", "rw+", "Magick Image File Format"),
  MNG("mng", "rw+", "Multiple-image Network Graphics"),
  MONO("mono", "rw-", "Bi-level bitmap in least-significant- -byte-first order"),
  MPC("mpc", "rw+", "Magick Persistent Cache image format"),
  MPEG("mpeg", "rw+", "MPEG-1 Video Stream"),
  MPG("mpg", "rw+", "MPEG-1 Video Stream"),
  MRW("mrw", "r--", "Minolta Photo Raw"),
  MSL("msl", "r--", "Magick Scripting Language"),
  MTV("mtv", "rw+", "MTV Raytracing image format"),
  MVG("mvg", "rw-", "Magick Vector Graphics"),
  NEF("nef", "r--", "Nikon Electronic Format"),
  NULL("null", "r--", "Constant image of uniform color"),
  OTB("otb", "rw-", "On-the-air bitmap"),
  P7("p7", "rw+", "Xv thumbnail format"),
  PAL("pal", "rw-", "16bit/pixel interleaved YUV"),
  PALM("palm", "rw-", "Palm Pixmap"),
  PBM("pbm", "rw+", "Portable bitmap format (black and white)"),
  PCD("pcd", "rw-", "Photo CD"),
  PCDS("pcds", "rw-", "Photo CD"),
  PCL("pcl", "-w-", "Page Control Language"),
  PCT("pct", "rw-", "Apple Macintosh QuickDraw/PICT"),
  PCX("pcx", "rw-", "ZSoft IBM PC Paintbrush"),
  PDB("pdb", "rw+", "Palm Database ImageViewer Format"),
  PDF("pdf", "rw+", "Portable Document Format"),
  PEF("pef", "r--", "Pentax Electronic File"),
  PFA("pfa", "r--", "TrueType font"),
  PFB("pfb", "r--", "TrueType font"),
  PGM("pgm", "rw+", "Portable graymap format (gray scale)"),
  PGX("pgx", "r--", "JPEG-2000 VM Format"),
  PICON("picon", "rw-", "Personal Icon"),
  PICT("pict", "rw-", "Apple Macintosh QuickDraw/PICT"),
  PIX("pix", "r--", "Alias/Wavefront RLE image format"),
  PLASMA("plasma", "r--", "Plasma fractal image"),
  PNG("png", "rw-", "Portable Network Graphics"),
  PNG24("png24", "rw-", "Portable Network Graphics, 24 bit RGB opaque only"),
  PNG32("png32", "rw-", "Portable Network Graphics, 32 bit RGBA semitransparency OK"),
  PNG8("png8", "rw-", "Portable Network Graphics, 8-bit indexed, binary transparency only"),
  PNM("pnm", "rw+", "Portable anymap"),
  PPM("ppm", "rw+", "Portable pixmap format (color)"),
  PREVIEW("preview", "-w-", "Show a preview an image enhancement,effect, or f/x"),
  PS("ps", "rw+", "Adobe PostScript"),
  PS2("ps2", "-w+", "Adobe Level II PostScript"),
  PS3("ps3", "-w+", "Adobe Level III PostScript"),
  PSD("psd", "rw-", "Adobe Photoshop bitmap"),
  PTIF("ptif", "rw-", "Pyramid encoded TIFF"),
  PWP("pwp", "r--", "Seattle Film Works"),
  RAF("raf", "r--", "Fuji Photo RAW"),
  RAS("ras", "rw+", "SUN Rasterfile"),
  RGB("rgb", "rw+", "Raw red, green, and blue samples"),
  RGBA("rgba", "rw+", "Raw red, green, blue, and matte samples"),
  RLA("rla", "r--", "Alias/Wavefront image"),
  RLE("rle", "r--", "Utah Run length encoded image"),
  SCT("sct", "r--", "Scitex HandShake"),
  SFW("sfw", "r--", "Seattle Film Works"),
  SGI("sgi", "rw+", "Irix RGB image"),
  SHTML("shtml", "-w-", "Hypertext Markup Language and a client-side image map"),
  STEGANO("stegano", "r--", "Steganographic image"),
  SUN("sun", "rw+", "SUN Rasterfile"),
  SVG("svg", "rw+", "Scalable Vector Gaphics"),
  TEXT("text", "rw+", "Raw text"),
  TGA("tga", "rw+", "Truevision Targa image"),
  TIFF("tiff", "rw+", "Tagged Image File Format"),
  TILE("tile", "r--", "Tile image with a texture"),
  TIM("tim", "r--", "PSX TIM"),
  TOPOL("topol", "r--", "TOPOL X Image"),
  TTF("ttf", "r--", "TrueType font"),
  TXT("txt", "rw+", "Raw text"),
  UIL("uil", "-w-", "X-Motif UIL table"),
  UYVY("uyvy", "rw-", "16bit/pixel interleaved YUV"),
  VDA("vda", "rw+", "Truevision Targa image"),
  VICAR("vicar", "rw-", "VICAR rasterfile format"),
  VID("vid", "rw+", "Visual Image Directory"),
  VIFF("viff", "rw+", "Khoros Visualization image"),
  VST("vst", "rw+", "Truevision Targa image"),
  WBMP("wbmp", "rw-", "Wireless Bitmap (level 0) image"),
  WMF("wmf", "r--", "Windows Metafile"),
  WPG("wpg", "r--", "Word Perfect Graphics"),
  X("x", "rw-", "X Image"),
  X3F("x3f", "r--", "Foveon X3 (Sigma/Polaroid) RAW"),
  XBM("xbm", "rw-", "X Windows system bitmap (black and white)"),
  XC("xc", "r--", "Constant image uniform color"),
  XCF("xcf", "r--", "GIMP image"),
  XMP("xmp", "rw-", "Adobe XML metadata"),
  XPM("xpm", "rw-", "X Windows system pixmap (color)"),
  XV("xv", "rw+", "Khoros Visualization image"),
  XWD("xwd", "rw-", "X Windows system window dump (color)"),
  YUV("yuv", "rw-", "CCIR 601 4:1:1 or 4:2:2 (8-bit only)");
  private final String name;
  private final String mode;
  private final String description;


}